const en = {
  app: {
    name: 'VivasayaMitra AI',
    tagline: 'Your Voice. Your Language. Your Decision.',
  },
  nav: {
    dashboard: 'Dashboard',
    assistant: 'AI Assistant',
    weather: 'Weather',
    crop: 'Crop Intelligence',
    whatIf: 'What-If Simulator',
    schemes: 'Govt. Schemes',
    analytics: 'Analytics',
    profile: 'Profile',
    settings: 'Settings',
    emergency: 'Emergency',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    getStarted: 'Get Started',
    tryDemo: 'Try Demo',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    close: 'Close',
    retry: 'Retry',
    loading: 'Loading...',
    submit: 'Submit',
    back: 'Back',
    next: 'Next',
    yes: 'Yes',
    no: 'No',
    online: 'Online',
    offline: 'Offline',
    poorConnection: 'Poor connection',
    demoMode: 'DEMO MODE',
    demoData: 'Demo data is being used',
    liveData: 'Live data',
    language: 'Language',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noData: 'No data available',
    confirm: 'Confirm',
    search: 'Search',
    clear: 'Clear',
    apply: 'Apply',
    viewAll: 'View all',
    today: 'Today',
    tomorrow: 'Tomorrow',
  },
  landing: {
    heroTitle: 'VivasayaMitra AI',
    heroTagline: 'Your Voice. Your Language. Your Decision.',
    heroDescription: 'An AI-powered multilingual decision-support platform helping small and marginal farmers make safer, smarter and more informed decisions.',
    problemTitle: 'The Problem',
    problemText: 'Small and marginal farmers in India face unpredictable weather, limited access to expert advice, language barriers, and complex government schemes. Decisions about when to sow, fertilize, irrigate, or harvest are often made without reliable information.',
    solutionTitle: 'The Solution',
    solutionText: 'VivasayaMitra AI combines voice-first interaction, multilingual support, weather intelligence, and a proactive risk engine to deliver explainable, actionable recommendations tailored to each farmer\u2019s profile.',
    howTitle: 'How It Works',
    howStep1: 'Speak or type your question in your language.',
    howStep2: 'AI analyses your profile, weather, and crop data.',
    howStep3: 'Get explainable risk scores and recommendations.',
    howStep4: 'Simulate decisions and find relevant schemes.',
    featuresTitle: 'Key Features',
    feature1: 'Multilingual voice-first interface',
    feature2: 'Proactive risk analysis engine',
    feature3: 'AI What-If decision simulator',
    feature4: 'Government scheme matcher',
    feature5: 'Offline & low-connectivity support',
    feature6: 'Professional analytics dashboard',
    multilingualTitle: 'Multilingual Support',
    multilingualText: 'The entire application adapts to English, Tamil, or Hindi. Every label, button, alert, and AI response switches instantly.',
    decisionTitle: 'AI Decision Engine',
    decisionText: 'A proactive risk engine combines weather, crop stage, soil, and irrigation data to generate a risk score and clear recommended actions.',
    whatIfTitle: 'What-If Simulator',
    whatIfText: 'Compare two farming decisions side by side with estimated risk, cost impact, and weather considerations.',
    offlineTitle: 'Offline Support',
    offlineText: 'Cached profile, recommendations, and emergency info remain accessible even without connectivity.',
    impactTitle: 'Built for Impact',
    impactText: 'Designed for small and marginal farmers who need practical, explainable, language-appropriate guidance.',
    ctaTitle: 'Ready to make smarter farming decisions?',
    ctaText: 'Get started or try the demo to see VivasayaMitra AI in action.',
  },
  auth: {
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to your account',
    registerTitle: 'Create Account',
    registerSubtitle: 'Join VivasayaMitra AI',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    phoneEmail: 'Phone or Email',
    phoneEmailPlaceholder: 'Enter phone or email',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    preferredLanguage: 'Preferred Language',
    location: 'Location',
    locationPlaceholder: 'e.g. Tamil Nadu',
    farmerType: 'Farmer Type',
    smallFarmer: 'Small Farmer',
    marginalFarmer: 'Marginal Farmer',
    noAccount: 'Don\u2019t have an account?',
    haveAccount: 'Already have an account?',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    loginSuccess: 'Login successful',
    registerSuccess: 'Account created successfully',
    loginError: 'Invalid credentials',
    registerError: 'Could not create account',
    demoLogin: 'Try Demo Account',
    demoNote: 'Use a demo farmer account to explore the platform.',
    validating: 'Please wait...',
    nameRequired: 'Full name is required',
    phoneRequired: 'Phone or email is required',
    passwordRequired: 'Password is required',
    passwordShort: 'Password must be at least 6 characters',
  },
  dashboard: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    dateLabel: 'Today',
    weatherRisk: 'Weather Risk',
    cropHealth: 'Crop Health',
    todayRecommendation: 'Today\u2019s Recommendation',
    farmRiskScore: 'Farm Risk Score',
    currentWeather: 'Current Weather',
    temperature: 'Temperature',
    rainProbability: 'Rain Probability',
    humidity: 'Humidity',
    wind: 'Wind Speed',
    recentAlerts: 'Recent Alerts',
    recommendedActions: 'Recommended Actions',
    cropStatus: 'Crop Status',
    noAlerts: 'No active alerts',
    noRecommendations: 'No recommendations yet',
    riskLow: 'Low Risk',
    riskModerate: 'Moderate Risk',
    riskHigh: 'High Risk',
    good: 'Good',
    needsAttention: 'Needs Attention',
    critical: 'Critical',
    viewDetails: 'View Details',
    overview: 'Overview',
    quickActions: 'Quick Actions',
    askAssistant: 'Ask AI Assistant',
    checkWeather: 'Check Weather',
    simulateDecision: 'Simulate Decision',
    findSchemes: 'Find Schemes',
  },
  assistant: {
    title: 'AI Farm Assistant',
    subtitle: 'Ask questions about your farm, weather, crops, and schemes',
    placeholder: 'Type your question...',
    send: 'Send',
    voiceInput: 'Voice Input',
    listening: 'Listening...',
    processing: 'Processing...',
    speaking: 'Speaking...',
    suggestedQuestions: 'Suggested Questions',
    conversationHistory: 'Conversation History',
    newConversation: 'New Conversation',
    noConversations: 'No conversations yet',
    demoNotice: 'Demo data is being used. AI responses are generated from a deterministic knowledge base.',
    micPermissionDenied: 'Microphone permission denied. Please allow microphone access in your browser settings.',
    voiceUnsupported: 'Voice input is not supported in this browser. You can still type your question.',
    stopSpeaking: 'Stop',
    clearChat: 'Clear Chat',
    riskLevel: 'Risk Level',
    why: 'Why',
    recommendedAction: 'Recommended Action',
    warning: 'Warning',
    sources: 'Sources',
    qRainTomorrow: 'Will it rain tomorrow?',
    qFertilizerToday: 'Can I apply fertilizer today?',
    qCropRisk: 'What is the risk to my crop?',
    qGovtScheme: 'What government scheme can I get?',
    qIrrigation: 'When should I irrigate my field?',
    qPest: 'How to prevent pest attacks?',
  },
  weather: {
    title: 'Weather Intelligence',
    subtitle: 'Current conditions and forecast for your location',
    currentConditions: 'Current Conditions',
    forecast: '7-Day Forecast',
    feelsLike: 'Feels Like',
    windSpeed: 'Wind Speed',
    weatherRisk: 'Weather Risk',
    rainExpected: 'Rain Expected',
    noRainExpected: 'No rain expected',
    demoNotice: 'Demo weather data is being used. Connect a weather API for live data.',
    refresh: 'Refresh',
    lastUpdated: 'Last updated',
    condition: 'Condition',
    sunny: 'Sunny',
    cloudy: 'Cloudy',
    rainy: 'Rainy',
    partlyCloudy: 'Partly Cloudy',
    thunderstorm: 'Thunderstorm',
    clear: 'Clear',
  },
  crop: {
    title: 'Crop Intelligence',
    subtitle: 'Monitor your crop health and risks',
    selectedCrop: 'Selected Crop',
    cropStage: 'Crop Stage',
    currentRisk: 'Current Risk',
    riskFactors: 'Common Risk Factors',
    recommendedActions: 'Recommended Actions',
    monitoringChecklist: 'Monitoring Checklist',
    updateStage: 'Update Crop Stage',
    stageUpdated: 'Crop stage updated successfully',
    selectStage: 'Select a stage',
    stages: {
      seeding: 'Seeding',
      vegetative: 'Vegetative',
      flowering: 'Flowering',
      grainFilling: 'Grain Filling',
      maturity: 'Maturity',
      harvest: 'Harvest',
    },
    noCropSelected: 'No crop selected. Update your profile to add a crop.',
    healthStatus: 'Health Status',
    daysToHarvest: 'Days to Harvest',
    growthProgress: 'Growth Progress',
  },
  whatIf: {
    title: 'What-If Decision Simulator',
    subtitle: 'Compare farming decisions before you act',
    scenarioLabel: 'Scenario',
    scenarioPlaceholder: 'e.g. Apply fertilizer today vs wait 3 days',
    optionA: 'Option A',
    optionB: 'Option B',
    optionALabel: 'First option',
    optionBLabel: 'Second option',
    simulate: 'Simulate',
    riskScore: 'Risk Score',
    weatherImpact: 'Weather Impact',
    costImpact: 'Cost Impact',
    potentialBenefit: 'Potential Benefit',
    recommendation: 'Recommendation',
    explanation: 'Explanation',
    result: 'Simulation Result',
    betterOption: 'Better Option',
    disclaimer: 'AI-assisted scenario estimate. Not guaranteed agricultural fact.',
    history: 'Simulation History',
    noHistory: 'No simulations yet',
    scenarios: {
      fertilizer: 'Apply fertilizer today vs wait 3 days',
      irrigate: 'Irrigate now vs wait for rain',
      harvest: 'Harvest now vs wait 1 week',
      pesticide: 'Apply pesticide now vs monitor 2 days',
    },
  },
  schemes: {
    title: 'Government Scheme Matcher',
    subtitle: 'Find schemes you may be eligible for',
    state: 'State',
    farmerType: 'Farmer Type',
    landSize: 'Land Size (acres)',
    crop: 'Crop',
    ageGroup: 'Age Group',
    category: 'Category',
    findSchemes: 'Find Schemes',
    matchingSchemes: 'Matching Schemes',
    noMatch: 'No matching schemes found. Try adjusting your criteria.',
    schemeName: 'Scheme Name',
    purpose: 'Purpose',
    eligibility: 'Eligibility',
    documents: 'Required Documents',
    applicationSteps: 'Application Steps',
    officialLink: 'Official Link',
    verifyNote: 'Eligibility should be verified on the official government portal before applying.',
    allCategories: 'All Categories',
    categories: {
      subsidy: 'Subsidy',
      insurance: 'Insurance',
      loan: 'Loan',
      pension: 'Pension',
      equipment: 'Equipment',
      irrigation: 'Irrigation',
      soil: 'Soil Health',
      income: 'Income Support',
    },
  },
  analytics: {
    title: 'Analytics Dashboard',
    subtitle: 'Track platform usage and impact',
    demoLabel: 'Prototype / Demo Metrics',
    totalRecommendations: 'Total Recommendations',
    riskAlerts: 'Risk Alerts',
    highRiskCases: 'High-Risk Cases',
    languagesUsed: 'Languages Used',
    voiceInteractions: 'Voice Interactions',
    whatIfSimulations: 'What-If Simulations',
    offlineSessions: 'Offline Sessions',
    recommendationsOverTime: 'Recommendations Over Time',
    riskDistribution: 'Risk Distribution',
    languageDistribution: 'Language Distribution',
    eventBreakdown: 'Event Breakdown',
    noData: 'No analytics data yet. Start using the app to generate metrics.',
  },
  profile: {
    title: 'Farmer Profile',
    subtitle: 'Your personal and farm information',
    personal: 'Personal Information',
    farm: 'Farm Information',
    financial: 'Financial Information',
    fullName: 'Full Name',
    phone: 'Phone',
    preferredLanguage: 'Preferred Language',
    location: 'Location',
    state: 'State',
    farmerType: 'Farmer Type',
    smallFarmer: 'Small Farmer',
    marginalFarmer: 'Marginal Farmer',
    farmSize: 'Farm Size (acres)',
    crop: 'Crop',
    cropVariety: 'Crop Variety',
    cropStage: 'Crop Stage',
    soilType: 'Soil Type',
    irrigationType: 'Irrigation Type',
    budget: 'Approximate Budget (INR)',
    farmingObjective: 'Farming Objective',
    save: 'Save Profile',
    saved: 'Profile saved successfully',
    saveError: 'Could not save profile',
    selectCrop: 'Select crop',
    selectStage: 'Select stage',
    selectSoil: 'Select soil type',
    selectIrrigation: 'Select irrigation type',
    crops: {
      paddy: 'Paddy',
      wheat: 'Wheat',
      cotton: 'Cotton',
      sugarcane: 'Sugarcane',
      maize: 'Maize',
      groundnut: 'Groundnut',
      pulses: 'Pulses',
      vegetables: 'Vegetables',
    },
    soilTypes: {
      clay: 'Clay',
      loam: 'Loam',
      sandy: 'Sandy',
      black: 'Black',
      red: 'Red',
      alluvial: 'Alluvial',
    },
    irrigationTypes: {
      drip: 'Drip',
      sprinkler: 'Sprinkler',
      canal: 'Canal',
      borewell: 'Borewell',
      rainfed: 'Rainfed',
      flood: 'Flood',
    },
    objectives: {
      yield: 'Maximize Yield',
      profit: 'Maximize Profit',
      sustainability: 'Sustainable Farming',
      riskReduction: 'Reduce Risk',
    },
  },
  emergency: {
    title: 'Emergency Mode',
    subtitle: 'Critical information and safety guidance',
    severeWeather: 'Severe Weather Warning',
    safetyInstructions: 'Safety Instructions',
    emergencyInfo: 'Emergency Information',
    locationInfo: 'Location Information',
    officialLinks: 'Official Links',
    callEmergency: 'Call Emergency',
    offlineNote: 'This information is available offline.',
    instructions: [
      'Move to a safe, elevated location if flooding is expected.',
      'Secure loose items that could be blown away by strong winds.',
      'Keep emergency contacts and important documents in a waterproof bag.',
      'Do not attempt to cross flooded roads or waterways.',
      'Stay indoors during thunderstorms and avoid open fields.',
      'Keep your phone charged and maintain communication with family.',
    ],
    contacts: {
      ndrf: 'NDRF Helpline: 1070',
      disaster: 'Disaster Management: 108',
      police: 'Police: 100',
      ambulance: 'Ambulance: 108',
      agriculture: 'Kisan Call Center: 1800 180 1551',
    },
  },
  settings: {
    title: 'Settings',
    subtitle: 'Customize your experience',
    language: 'Application Language',
    languageDescription: 'Changes the entire application interface language.',
    notifications: 'Notifications',
    notificationsDescription: 'Enable or disable push notifications.',
    voice: 'Voice Settings',
    voiceDescription: 'Configure voice input and output.',
    autoSpeak: 'Auto-speak AI responses',
    speechRate: 'Speech rate',
    dataManagement: 'Data Management',
    clearCache: 'Clear cached data',
    clearCacheDescription: 'Remove offline cached data.',
    cacheCleared: 'Cache cleared successfully',
    about: 'About',
    aboutText: 'VivasayaMitra AI v1.0 \u2014 An AI-powered multilingual decision-support platform for small and marginal farmers.',
    enableNotifications: 'Enable Notifications',
  },
  network: {
    online: 'Online',
    offline: 'Offline',
    poor: 'Poor connection',
    offlineBanner: 'You are offline. Cached data is available. Some features may be limited.',
    poorBanner: 'Your connection is weak. Some features may be slower.',
    reconnecting: 'Reconnecting...',
  },
  errors: {
    fetchFailed: 'Could not load data. Please try again.',
    saveFailed: 'Could not save. Please try again.',
    sessionExpired: 'Your session has expired. Please log in again.',
    somethingWrong: 'Something went wrong.',
    notFound: 'Page not found.',
    unauthorized: 'Please log in to access this page.',
    liveUnavailable: 'Live service unavailable. Showing demo data.',
  },
  validation: {
    required: 'This field is required',
    invalidPhone: 'Please enter a valid phone number or email',
    invalidNumber: 'Please enter a valid number',
  },
};

export default en;
