const hi = {
  app: {
    name: 'विवसायमित्र AI',
    tagline: 'आपकी आवाज़. आपकी भाषा. आपका निर्णय.',
  },
  nav: {
    dashboard: 'डैशबोर्ड',
    assistant: 'AI सहायक',
    weather: 'मौसम',
    crop: 'फसल खुफिया',
    whatIf: 'क्या-हो यदि सिम्युलेटर',
    schemes: 'सरकारी योजनाएं',
    analytics: 'विश्लेषण',
    profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    emergency: 'आपातकाल',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    getStarted: 'शुरू करें',
    tryDemo: 'डेमो आज़माएं',
  },
  common: {
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    close: 'बंद करें',
    retry: 'पुनः प्रयास',
    loading: 'लोड हो रहा है...',
    submit: 'जमा करें',
    back: 'वापस',
    next: 'अगला',
    yes: 'हां',
    no: 'नहीं',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    poorConnection: 'खराब कनेक्शन',
    demoMode: 'डेमो मोड',
    demoData: 'डेमो डेटा उपयोग किया जा रहा है',
    liveData: 'लाइव डेटा',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    markAllRead: 'सभी पढ़ा हुआ चिह्नित करें',
    noData: 'कोई डेटा उपलब्ध नहीं',
    confirm: 'पुष्टि करें',
    search: 'खोजें',
    clear: 'साफ़ करें',
    apply: 'लागू करें',
    viewAll: 'सभी देखें',
    today: 'आज',
    tomorrow: 'कल',
  },
  landing: {
    heroTitle: 'विवसायमित्र AI',
    heroTagline: 'आपकी आवाज़. आपकी भाषा. आपका निर्णय.',
    heroDescription: 'एक AI-संचालित बहुभाषीय निर्णय-सहायता मंच जो छोटे और सीमांत किसानों को सुरक्षित, समझदार और जानकारी से भरपूर निर्णय लेने में मदद करता है।',
    problemTitle: 'समस्या',
    problemText: 'भारत में छोटे और सीमांत किसान अप्रत्याशित मौसम, विशेषज्ञ सलाह तक सीमित पहुंच, भाषा बाधाओं और जटिल सरकारी योजनाओं का सामना करते हैं।',
    solutionTitle: 'समाधान',
    solutionText: 'विवसायमित्र AI आवाज़-प्रथम संवाद, बहुभाषीय समर्थन, मौसम खुफिया और सक्रिय जोखिम इंजन को जोड़ता है।',
    howTitle: 'यह कैसे काम करता है',
    howStep1: 'अपनी भाषा में प्रश्न पूछें या टाइप करें।',
    howStep2: 'AI आपकी प्रोफ़ाइल, मौसम और फसल डेटा का विश्लेषण करता है।',
    howStep3: 'स्पष्टीकरण योग्य जोखिम स्कोर और सिफारिशें प्राप्त करें।',
    howStep4: 'निर्णयों का अनुकरण करें और संबंधित योजनाएं खोजें।',
    featuresTitle: 'मुख्य विशेषताएं',
    feature1: 'बहुभाषीय आवाज़-प्रथम इंटरफ़ेस',
    feature2: 'सक्रिय जोखिम विश्लेषण इंजन',
    feature3: 'AI क्या-हो यदि निर्णय सिम्युलेटर',
    feature4: 'सरकारी योजना मैचर',
    feature5: 'ऑफ़लाइन और कम-कनेक्टिविटी समर्थन',
    feature6: 'पेशेवर विश्लेषण डैशबोर्ड',
    multilingualTitle: 'बहुभाषीय समर्थन',
    multilingualText: 'पूरा एप्लिकेशन अंग्रेज़ी, तमिल या हिंदी के अनुसार बदलता है। हर लेबल, बटन, अलर्ट और AI प्रतिक्रिया तुरंत बदलती है।',
    decisionTitle: 'AI निर्णय इंजन',
    decisionText: 'एक सक्रिय जोखिम इंजन मौसम, फसल चरण, मिट्टी और सिंचाई डेटा को जोड़कर जोखिम स्कोर और स्पष्ट सिफारिशें बनाता है।',
    whatIfTitle: 'क्या-हो यदि सिम्युलेटर',
    whatIfText: 'अनुमानित जोखिम, लागत प्रभाव और मौसम विचारों के साथ दो कृषि निर्णयों की तुलना करें।',
    offlineTitle: 'ऑफ़लाइन समर्थन',
    offlineText: 'कनेक्टिविटी के बिना भी कैश्ड प्रोफ़ाइल, सिफारिशें और आपातकालीन जानकारी उपलब्ध रहती है।',
    impactTitle: 'प्रभाव के लिए निर्मित',
    impactText: 'व्यावहारिक, स्पष्टीकरण योग्य, भाषा-उपयुक्त मार्गदर्शन चाहिए वाले छोटे और सीमांत किसानों के लिए डिज़ाइन किया गया।',
    ctaTitle: 'समझदार कृषि निर्णय लेने के लिए तैयार हैं?',
    ctaText: 'शुरू करें या विवसायमित्र AI को क्रिया में देखने के लिए डेमो आज़माएं।',
  },
  auth: {
    loginTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने खाते में लॉगिन करें',
    registerTitle: 'खाता बनाएं',
    registerSubtitle: 'विवसायमित्र AI में शामिल हों',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
    phoneEmail: 'फ़ोन या ईमेल',
    phoneEmailPlaceholder: 'फ़ोन या ईमेल दर्ज करें',
    password: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    preferredLanguage: 'पसंदीदा भाषा',
    location: 'स्थान',
    locationPlaceholder: 'जैसे तमिलनाडु',
    farmerType: 'किसान प्रकार',
    smallFarmer: 'छोटा किसान',
    marginalFarmer: 'सीमांत किसान',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    loginSuccess: 'लॉगिन सफल',
    registerSuccess: 'खाता सफलतापूर्वक बनाया गया',
    loginError: 'अमान्य क्रेडेंशियल',
    registerError: 'खाता नहीं बनाया जा सका',
    demoLogin: 'डेमो खाता आज़माएं',
    demoNote: 'मंच का अन्वेषण करने के लिए डेमो किसान खाते का उपयोग करें।',
    validating: 'कृपया प्रतीक्षा करें...',
    nameRequired: 'पूरा नाम आवश्यक है',
    phoneRequired: 'फ़ोन या ईमेल आवश्यक है',
    passwordRequired: 'पासवर्ड आवश्यक है',
    passwordShort: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
  },
  dashboard: {
    greetingMorning: 'सुप्रभात',
    greetingAfternoon: 'नमस्कार',
    greetingEvening: 'शुभ संध्या',
    dateLabel: 'आज',
    weatherRisk: 'मौसम जोखिम',
    cropHealth: 'फसल स्वास्थ्य',
    todayRecommendation: 'आज की सिफारिश',
    farmRiskScore: 'फार्म जोखिम स्कोर',
    currentWeather: 'वर्तमान मौसम',
    temperature: 'तापमान',
    rainProbability: 'बारिश संभावना',
    humidity: 'नमी',
    wind: 'हवा की गति',
    recentAlerts: 'हाल की चेतावनी',
    recommendedActions: 'अनुशंसित कार्य',
    cropStatus: 'फसल स्थिति',
    noAlerts: 'कोई सक्रिय चेतावनी नहीं',
    noRecommendations: 'अभी तक कोई सिफारिश नहीं',
    riskLow: 'कम जोखिम',
    riskModerate: 'मध्यम जोखिम',
    riskHigh: 'उच्च जोखिम',
    good: 'अच्छा',
    needsAttention: 'ध्यान चाहिए',
    critical: 'गंभीर',
    viewDetails: 'विवरण देखें',
    overview: 'अवलोकन',
    quickActions: 'त्वरित कार्य',
    askAssistant: 'AI सहायक से पूछें',
    checkWeather: 'मौसम जांचें',
    simulateDecision: 'निर्णय अनुकरण करें',
    findSchemes: 'योजनाएं खोजें',
  },
  assistant: {
    title: 'AI कृषि सहायक',
    subtitle: 'अपने खेत, मौसम, फसलों और योजनाओं के बारे में प्रश्न पूछें',
    placeholder: 'अपना प्रश्न टाइप करें...',
    send: 'भेजें',
    voiceInput: 'आवाज़ इनपुट',
    listening: 'सुन रहा है...',
    processing: 'प्रोसेस कर रहा है...',
    speaking: 'बोल रहा है...',
    suggestedQuestions: 'सुझाए गए प्रश्न',
    conversationHistory: 'वार्तालाप इतिहास',
    newConversation: 'नई वार्तालाप',
    noConversations: 'अभी तक कोई वार्तालाप नहीं',
    demoNotice: 'डेमो डेटा उपयोग किया जा रहा है। AI प्रतिक्रियाएं निर्धारक ज्ञान आधार से उत्पन्न होती हैं।',
    micPermissionDenied: 'माइक्रोफ़ोन अनुमति अस्वीकृत। अपने ब्राउज़र सेटिंग्स में माइक्रोफ़ोन पहुंच की अनुमति दें।',
    voiceUnsupported: 'इस ब्राउज़र में आवाज़ इनपुट समर्थित नहीं है। आप अभी भी अपना प्रश्न टाइप कर सकते हैं।',
    stopSpeaking: 'रोकें',
    clearChat: 'चैट साफ़ करें',
    riskLevel: 'जोखिम स्तर',
    why: 'क्यों',
    recommendedAction: 'अनुशंसित कार्य',
    warning: 'चेतावनी',
    sources: 'स्रोत',
    qRainTomorrow: 'कल बारिश होगी?',
    qFertilizerToday: 'आज खाद डालना सही है?',
    qCropRisk: 'मेरी फसल के लिए क्या जोखिम है?',
    qGovtScheme: 'मुझे कौन सी सरकारी योजना मिल सकती है?',
    qIrrigation: 'मुझे सिंचाई कब करनी चाहिए?',
    qPest: 'कीट आक्रमण कैसे रोकें?',
  },
  weather: {
    title: 'मौसम खुफिया',
    subtitle: 'आपके स्थान के लिए वर्तमान स्थितियां और पूर्वानुमान',
    currentConditions: 'वर्तमान स्थितियां',
    forecast: '7-दिन पूर्वानुमान',
    feelsLike: 'महसूस होता है',
    windSpeed: 'हवा की गति',
    weatherRisk: 'मौसम जोखिम',
    rainExpected: 'बारिश की संभावना',
    noRainExpected: 'बारिश नहीं होगी',
    demoNotice: 'डेमो मौसम डेटा उपयोग किया जा रहा है। लाइव डेटा के लिए मौसम API जोड़ें।',
    refresh: 'रिफ्रेश',
    lastUpdated: 'अंतिम अपडेट',
    condition: 'स्थिति',
    sunny: 'धूप',
    cloudy: 'बादल',
    rainy: 'बारिश',
    partlyCloudy: 'आंशिक बादल',
    thunderstorm: 'गरज के साथ बारिश',
    clear: 'साफ़',
  },
  crop: {
    title: 'फसल खुफिया',
    subtitle: 'अपनी फसल स्वास्थ्य और जोखिम की निगरानी करें',
    selectedCrop: 'चयनित फसल',
    cropStage: 'फसल चरण',
    currentRisk: 'वर्तमान जोखिम',
    riskFactors: 'सामान्य जोखिम कारक',
    recommendedActions: 'अनुशंसित कार्य',
    monitoringChecklist: 'निगरानी चेकलिस्ट',
    updateStage: 'फसल चरण अपडेट करें',
    stageUpdated: 'फसल चरण सफलतापूर्वक अपडेट किया गया',
    selectStage: 'एक चरण चुनें',
    stages: {
      seeding: 'बुवाई',
      vegetative: 'वानस्पतिक वृद्धि',
      flowering: 'फूल आना',
      grainFilling: 'दाना भरना',
      maturity: 'परिपक्वता',
      harvest: 'कटाई',
    },
    noCropSelected: 'कोई फसल चयनित नहीं। फसल जोड़ने के लिए अपनी प्रोफ़ाइल अपडेट करें।',
    healthStatus: 'स्वास्थ्य स्थिति',
    daysToHarvest: 'कटाई तक दिन',
    growthProgress: 'वृद्धि प्रगति',
  },
  whatIf: {
    title: 'क्या-हो यदि निर्णय सिम्युलेटर',
    subtitle: 'कार्य करने से पहले कृषि निर्णयों की तुलना करें',
    scenarioLabel: 'परिदृश्य',
    scenarioPlaceholder: 'जैसे आज खाद डालें बनाम 3 दिन प्रतीक्षा',
    optionA: 'विकल्प A',
    optionB: 'विकल्प B',
    optionALabel: 'पहला विकल्प',
    optionBLabel: 'दूसरा विकल्प',
    simulate: 'अनुकरण करें',
    riskScore: 'जोखिम स्कोर',
    weatherImpact: 'मौसम प्रभाव',
    costImpact: 'लागत प्रभाव',
    potentialBenefit: 'संभावित लाभ',
    recommendation: 'सिफारिश',
    explanation: 'व्याख्या',
    result: 'अनुकरण परिणाम',
    betterOption: 'बेहतर विकल्प',
    disclaimer: 'AI-सहायित परिदृश्य अनुमान। गारंटीशुदा कृषि तथ्य नहीं।',
    history: 'अनुकरण इतिहास',
    noHistory: 'अभी तक कोई अनुकरण नहीं',
    scenarios: {
      fertilizer: 'आज खाद डालें बनाम 3 दिन प्रतीक्षा',
      irrigate: 'अभी सिंचाई बनाम बारिश की प्रतीक्षा',
      harvest: 'अभी कटाई बनाम 1 सप्ताह प्रतीक्षा',
      pesticide: 'अभी कीटनाशक बनाम 2 दिन निगरानी',
    },
  },
  schemes: {
    title: 'सरकारी योजना मैचर',
    subtitle: 'ऐसी योजनाएं खोजें जिनके लिए आप पात्र हो सकते हैं',
    state: 'राज्य',
    farmerType: 'किसान प्रकार',
    landSize: 'भूमि आकार (एकड़)',
    crop: 'फसल',
    ageGroup: 'आयु वर्ग',
    category: 'श्रेणी',
    findSchemes: 'योजनाएं खोजें',
    matchingSchemes: 'मेल खाती योजनाएं',
    noMatch: 'कोई मेल खाती योजना नहीं मिली। अपने मानदंड समायोजित करने का प्रयास करें।',
    schemeName: 'योजना नाम',
    purpose: 'उद्देश्य',
    eligibility: 'पात्रता',
    documents: 'आवश्यक दस्तावेज़',
    applicationSteps: 'आवेदन चरण',
    officialLink: 'आधिकारिक लिंक',
    verifyNote: 'आवेदन करने से पहले आधिकारिक सरकारी पोर्टल पर पात्रता सत्यापित करें।',
    allCategories: 'सभी श्रेणियां',
    categories: {
      subsidy: 'सब्सिडी',
      insurance: 'बीमा',
      loan: 'ऋण',
      pension: 'पेंशन',
      equipment: 'उपकरण',
      irrigation: 'सिंचाई',
      soil: 'मिट्टी स्वास्थ्य',
      income: 'आय सहायता',
    },
  },
  analytics: {
    title: 'विश्लेषण डैशबोर्ड',
    subtitle: 'मंच उपयोग और प्रभाव को ट्रैक करें',
    demoLabel: 'प्रोटोटाइप / डेमो मेट्रिक्स',
    totalRecommendations: 'कुल सिफारिशें',
    riskAlerts: 'जोखिम चेतावनी',
    highRiskCases: 'उच्च-जोखिम मामले',
    languagesUsed: 'उपयोग की गई भाषाएं',
    voiceInteractions: 'आवाज़ संवाद',
    whatIfSimulations: 'क्या-हो यदि अनुकरण',
    offlineSessions: 'ऑफ़लाइन सत्र',
    recommendationsOverTime: 'समय के साथ सिफारिशें',
    riskDistribution: 'जोखिम वितरण',
    languageDistribution: 'भाषा वितरण',
    eventBreakdown: 'घटना विश्लेषण',
    noData: 'अभी तक कोई विश्लेषण डेटा नहीं। मेट्रिक्स उत्पन्न करने के लिए ऐप का उपयोग शुरू करें।',
  },
  profile: {
    title: 'किसान प्रोफ़ाइल',
    subtitle: 'आपकी व्यक्तिगत और खेत जानकारी',
    personal: 'व्यक्तिगत जानकारी',
    farm: 'खेत जानकारी',
    financial: 'वित्तीय जानकारी',
    fullName: 'पूरा नाम',
    phone: 'फ़ोन',
    preferredLanguage: 'पसंदीदा भाषा',
    location: 'स्थान',
    state: 'राज्य',
    farmerType: 'किसान प्रकार',
    smallFarmer: 'छोटा किसान',
    marginalFarmer: 'सीमांत किसान',
    farmSize: 'खेत आकार (एकड़)',
    crop: 'फसल',
    cropVariety: 'फसल किस्म',
    cropStage: 'फसल चरण',
    soilType: 'मिट्टी प्रकार',
    irrigationType: 'सिंचाई प्रकार',
    budget: 'अनुमानित बजट (रुपये)',
    farmingObjective: 'कृषि उद्देश्य',
    save: 'प्रोफ़ाइल सहेजें',
    saved: 'प्रोफ़ाइल सफलतापूर्वक सहेजी गई',
    saveError: 'प्रोफ़ाइल सहेजी नहीं जा सकी',
    selectCrop: 'फसल चुनें',
    selectStage: 'चरण चुनें',
    selectSoil: 'मिट्टी प्रकार चुनें',
    selectIrrigation: 'सिंचाई प्रकार चुनें',
    crops: {
      paddy: 'धान',
      wheat: 'गेहूं',
      cotton: 'कपास',
      sugarcane: 'गन्ना',
      maize: 'मक्का',
      groundnut: 'मूंगफली',
      pulses: 'दालें',
      vegetables: 'सब्जियां',
    },
    soilTypes: {
      clay: 'चिकनी मिट्टी',
      loam: 'दोमट',
      sandy: 'बलुई',
      black: 'काली',
      red: 'लाल',
      alluvial: 'जलोढ़',
    },
    irrigationTypes: {
      drip: 'टपक',
      sprinkler: 'छिड़काव',
      canal: 'नहर',
      borewell: 'बोरवेल',
      rainfed: 'वर्षा-आधारित',
      flood: 'बाढ़',
    },
    objectives: {
      yield: 'अधिकतम उपज',
      profit: 'अधिकतम लाभ',
      sustainability: 'टिकाऊ खेती',
      riskReduction: 'जोखिम कम करें',
    },
  },
  emergency: {
    title: 'आपातकाल मोड',
    subtitle: 'महत्वपूर्ण जानकारी और सुरक्षा मार्गदर्शन',
    severeWeather: 'गंभीर मौसम चेतावनी',
    safetyInstructions: 'सुरक्षा निर्देश',
    emergencyInfo: 'आपातकालीन जानकारी',
    locationInfo: 'स्थान जानकारी',
    officialLinks: 'आधिकारिक लिंक',
    callEmergency: 'आपातकालीन कॉल',
    offlineNote: 'यह जानकारी ऑफ़लाइन उपलब्ध है।',
    instructions: [
      'बाढ़ की संभावना होने पर सुरक्षित, ऊंचे स्थान पर जाएं।',
      'तेज़ हवा से उड़ सकने वाली वस्तुओं को सुरक्षित करें।',
      'आपातकालीन संपर्क और महत्वपूर्ण दस्तावेज़ पानी-रोधक बैग में रखें।',
      'बाढ़ भरी सड़कों या जलमार्गों को पार करने का प्रयास न करें।',
      'गरज के साथ बारिश के दौरान घर के अंदर रहें, खुले खेतों से बचें।',
      'अपना फ़ोन चार्ज रखें और परिवार से संपर्क में रहें।',
    ],
    contacts: {
      ndrf: 'NDRF हेल्पलाइन: 1070',
      disaster: 'आपदा प्रबंधन: 108',
      police: 'पुलिस: 100',
      ambulance: 'एम्बुलेंस: 108',
      agriculture: 'किसान कॉल सेंटर: 1800 180 1551',
    },
  },
  settings: {
    title: 'सेटिंग्स',
    subtitle: 'अपने अनुभव को अनुकूलित करें',
    language: 'एप्लिकेशन भाषा',
    languageDescription: 'पूरे एप्लिकेशन इंटरफ़ेस की भाषा बदलता है।',
    notifications: 'सूचनाएं',
    notificationsDescription: 'पुश सूचनाएं सक्षम या अक्षम करें।',
    voice: 'आवाज़ सेटिंग्स',
    voiceDescription: 'आवाज़ इनपुट और आउटपुट कॉन्फ़िगर करें।',
    autoSpeak: 'AI प्रतिक्रियाएं स्वतः बोलें',
    speechRate: 'भाषण दर',
    dataManagement: 'डेटा प्रबंधन',
    clearCache: 'कैश्ड डेटा साफ़ करें',
    clearCacheDescription: 'ऑफ़लाइन कैश्ड डेटा हटाएं।',
    cacheCleared: 'कैश सफलतापूर्वक साफ़ किया गया',
    about: 'के बारे में',
    aboutText: 'विवसायमित्र AI v1.0 \u2014 छोटे और सीमांत किसानों के लिए AI-संचालित बहुभाषीय निर्णय-सहायता मंच।',
    enableNotifications: 'सूचनाएं सक्षम करें',
  },
  network: {
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    poor: 'खराब कनेक्शन',
    offlineBanner: 'आप ऑफ़लाइन हैं। कैश्ड डेटा उपलब्ध है। कुछ सुविधाएं सीमित हो सकती हैं।',
    poorBanner: 'आपका कनेक्शन कमज़ोर है। कुछ सुविधाएं धीमी हो सकती हैं।',
    reconnecting: 'पुनः कनेक्ट हो रहा है...',
  },
  errors: {
    fetchFailed: 'डेटा लोड नहीं हो सका। पुनः प्रयास करें।',
    saveFailed: 'सहेजा नहीं जा सका। पुनः प्रयास करें।',
    sessionExpired: 'आपका सत्र समाप्त हो गया है। पुनः लॉगिन करें।',
    somethingWrong: 'कुछ गलत हो गया।',
    notFound: 'पृष्ठ नहीं मिला।',
    unauthorized: 'इस पृष्ठ तक पहुंचने के लिए लॉगिन करें।',
    liveUnavailable: 'लाइव सेवा अनुपलब्ध। डेमो डेटा दिखाया जा रहा है।',
  },
  validation: {
    required: 'यह फ़ील्ड आवश्यक है',
    invalidPhone: 'कृपया वैध फ़ोन नंबर या ईमेल दर्ज करें',
    invalidNumber: 'कृपया वैध संख्या दर्ज करें',
  },
};

export default hi;
